/**
 * Nails By Rabiaa - Google Reviews Database
 * Sourced from Google Maps listing (4.9 ★ Rating, 240+ Total Reviews)
 * Dalmia Cement Factory Road, Callachi CHS, Karachi
 */

const GOOGLE_REVIEWS_DATA = [
  {
    id: "rev-1",
    author: "Mahnoor Tariq",
    avatarColor: "#e06287",
    initials: "MT",
    isLocalGuide: true,
    reviewsCount: 38,
    rating: 5,
    relativeTime: "2 days ago",
    serviceTag: "Bridal Nails & 3D Art",
    text: "Rabiaa is hands down the most talented nail artist in Karachi! I got my wedding nails done with custom 3D acrylic bows, micro-pearls, and soft French tips (exactly what I showed in my inspiration picture). They stayed flawless through all 3 days of my wedding and my honeymoon for 4+ weeks without a single gem falling off. Super hygienic and welcoming studio on Dalmia road. 10/10 recommended!",
    attachedPhoto: "assets/images/signature-bridal-3d-nails.png",
    likesCount: 14,
    responseFromOwner: "Thank you so much Mahnoor for trusting us on your big day! You looked stunning, and it was an absolute pleasure creating your bridal set. ❤️✨"
  },
  {
    id: "rev-2",
    author: "Areeba Siddiqui",
    avatarColor: "#9351b6",
    initials: "AS",
    isLocalGuide: true,
    reviewsCount: 19,
    rating: 5,
    relativeTime: "5 days ago",
    serviceTag: "Acrylic Extensions",
    text: "I've been getting acrylic extensions in Karachi for 3 years now, and nobody compares to Rabiaa's cuticle prep and structure shaping. My almond shaped French ombré set is immaculate. No burning under the lamp, no lifting, and the finishing is top tier luxury. 24/7 flexible booking makes it super convenient for working women!",
    attachedPhoto: "assets/images/french-ombre-almond.jpg",
    likesCount: 9,
    responseFromOwner: null
  },
  {
    id: "rev-3",
    author: "Zainab Fatima",
    avatarColor: "#2b8a3e",
    initials: "ZF",
    isLocalGuide: false,
    reviewsCount: 6,
    rating: 5,
    relativeTime: "1 week ago",
    serviceTag: "Russian Gel Manicure",
    text: "Cleanliness is 100%! All instruments were autoclaved and taken out of sealed sterilization pouches right in front of me. The Russian manicure was painless and my cuticles look completely edited in real life. The gel polish has zero chips after 3 weeks. Truly a 4.9-star experience!",
    attachedPhoto: "assets/images/russian-natural-biab.jpg",
    likesCount: 7,
    responseFromOwner: "Safety and hygiene are our #1 priority Zainab! Glad you loved your Russian manicure!"
  },
  {
    id: "rev-4",
    author: "Hania Khan",
    avatarColor: "#e67700",
    initials: "HK",
    isLocalGuide: true,
    reviewsCount: 52,
    rating: 5,
    relativeTime: "2 weeks ago",
    serviceTag: "3D Bows & Gems",
    text: "Got the trending Hailey Bieber glazed chrome finish with almond extensions. I keep getting compliments from colleagues and friends asking where I got them done. Rabiaa is so gentle, patient, and artistic with details. Dalmia Callachi location is safe with easy parking.",
    attachedPhoto: "assets/images/glazed-chrome-almond.jpg",
    likesCount: 11,
    responseFromOwner: null
  },
  {
    id: "rev-5",
    author: "Sana Mir",
    avatarColor: "#1098ad",
    initials: "SM",
    isLocalGuide: false,
    reviewsCount: 4,
    rating: 5,
    relativeTime: "3 weeks ago",
    serviceTag: "Bridal Nails & 3D Art",
    text: "Did a royal barat red stiletto set matching my bridal mehndi henna and heavy lehenga. Looked even better than Pinterest! The Swarovski crystals and 24k gold leaf are sealed so nothing snags on chiffon clothes. Best nail salon experience in Karachi.",
    attachedPhoto: "assets/images/royal-bridal-stiletto.jpg",
    likesCount: 18,
    responseFromOwner: "Wishing you a lifetime of happiness Sana! Thank you for the glowing review."
  },
  {
    id: "rev-6",
    author: "Dr. Maryam Bilal",
    avatarColor: "#d6336c",
    initials: "MB",
    isLocalGuide: true,
    reviewsCount: 27,
    rating: 5,
    relativeTime: "3 weeks ago",
    serviceTag: "BIAB / Builder Gel",
    text: "As a doctor, I constantly wash my hands with harsh soap and sanitizer, so regular nail polish never lasted more than 2 days. Rabiaa introduced me to BIAB (Builder in a Bottle) overlay. My natural nails have grown so strong without breaking, and the nude shimmer stays glossy for a month!",
    attachedPhoto: null,
    likesCount: 15,
    responseFromOwner: null
  },
  {
    id: "rev-7",
    author: "Khadija Rehman",
    avatarColor: "#7048e8",
    initials: "KR",
    isLocalGuide: false,
    reviewsCount: 8,
    rating: 5,
    relativeTime: "1 month ago",
    serviceTag: "Deluxe Spa Pedicure",
    text: "The foot spa and pedicure here is heavenly. Thorough dead skin removal, relaxing rose petal massage, and high-shine French gel polish on toes. The studio ambiance is intimate, calming, and aesthetic.",
    attachedPhoto: "assets/images/deluxe-spa-pedicure.jpg",
    likesCount: 5,
    responseFromOwner: null
  },
  {
    id: "rev-8",
    author: "Alizeh Farooq",
    avatarColor: "#f76707",
    initials: "AF",
    isLocalGuide: true,
    reviewsCount: 41,
    rating: 4,
    relativeTime: "1 month ago",
    serviceTag: "Acrylic Extensions",
    text: "Great work and extreme precision! Rabiaa is a perfectionist. Only reason for 4 stars instead of 5 is that appointments book out very fast, so make sure to reserve your slot at least 3-4 days in advance via WhatsApp. But once you're on the chair, the work is 100% worth the wait.",
    attachedPhoto: null,
    likesCount: 12,
    responseFromOwner: "Thank you Alizeh! Yes, we recommend booking ahead as we keep single-client slots for dedicated attention. See you soon!"
  },
  {
    id: "rev-9",
    author: "Natasha Pervez",
    avatarColor: "#c2255c",
    initials: "NP",
    isLocalGuide: false,
    reviewsCount: 11,
    rating: 5,
    relativeTime: "1 month ago",
    serviceTag: "French Ombré",
    text: "The blend in her baby boomer / French ombré is smooth like butter! No harsh lines, perfect C-curve apex on the extensions, and thin natural-looking edges so they don't feel heavy at all. Will definitely be a regular client.",
    attachedPhoto: "assets/images/french-ombre-almond.jpg",
    likesCount: 8,
    responseFromOwner: null
  },
  {
    id: "rev-10",
    author: "Nimra Sheikh",
    avatarColor: "#15aabf",
    initials: "NS",
    isLocalGuide: true,
    reviewsCount: 22,
    rating: 5,
    relativeTime: "2 months ago",
    serviceTag: "3D Bows & Gems",
    text: "Obsessed is an understatement! I brought in an intricate Pinterest design with 3D acrylic ribbons and hearts, and Rabiaa recreated it to perfection with pastel syrup jelly glaze. High quality imported products used—no chemical fumes or pungent smell.",
    attachedPhoto: "assets/images/korean-jelly-bows.jpg",
    likesCount: 10,
    responseFromOwner: null
  },
  {
    id: "rev-11",
    author: "Rameen Waqar",
    avatarColor: "#845ef7",
    initials: "RW",
    isLocalGuide: false,
    reviewsCount: 3,
    rating: 5,
    relativeTime: "2 months ago",
    serviceTag: "Russian Gel Manicure",
    text: "Super professional! The studio is spotless and the tea/coffee hospitality is a lovely touch. Cuticle cleaning without any nicks or bleeding. My nails look so clean and elegant.",
    attachedPhoto: null,
    likesCount: 4,
    responseFromOwner: null
  },
  {
    id: "rev-12",
    author: "Syeda Anam",
    avatarColor: "#d9480f",
    initials: "SA",
    isLocalGuide: true,
    reviewsCount: 64,
    rating: 5,
    relativeTime: "2 months ago",
    serviceTag: "Bridal Nails & 3D Art",
    text: "Booked Rabiaa for my sister's Nikah and my own Barat nails. We both got custom sculpted sets with 3D bows and pearls. Everyone at the reception was asking about our nails! Rabiaa is so sweet and accommodating with time slots.",
    attachedPhoto: "assets/images/signature-bridal-3d-nails.png",
    likesCount: 21,
    responseFromOwner: "Such an honor to do nails for both lovely sisters! Thank you Anam! 💕"
  },
  {
    id: "rev-13",
    author: "Laiba Noor",
    avatarColor: "#4c6ef5",
    initials: "LN",
    isLocalGuide: false,
    reviewsCount: 7,
    rating: 5,
    relativeTime: "3 months ago",
    serviceTag: "Acrylic Extensions",
    text: "Long coffin shape with cat-eye velvet magnetic gel polish. Absolutely stunning in direct sunlight! They lasted through typing 8 hours a day for over a month with zero cracks.",
    attachedPhoto: "assets/images/velvet-cateye-coffin.jpg",
    likesCount: 6,
    responseFromOwner: null
  },
  {
    id: "rev-14",
    author: "Iqra Jawed",
    avatarColor: "#be4bdb",
    initials: "IJ",
    isLocalGuide: true,
    reviewsCount: 31,
    rating: 5,
    relativeTime: "3 months ago",
    serviceTag: "BIAB / Builder Gel",
    text: "Rabiaa cured my nail-biting habit! Her BIAB treatment helped my short damaged nails recover. She gave them a cute subtle nude pink overlay with chrome dust. So grateful to have found this gem in Karachi.",
    attachedPhoto: "assets/images/russian-natural-biab.jpg",
    likesCount: 16,
    responseFromOwner: "So happy to see your nail health journey flourish Iqra! Keep shining!"
  },
  {
    id: "rev-15",
    author: "Fatima Zahra",
    avatarColor: "#20c997",
    initials: "FZ",
    isLocalGuide: false,
    reviewsCount: 5,
    rating: 5,
    relativeTime: "3 months ago",
    serviceTag: "Russian Gel Manicure",
    text: "Five stars for hygiene and detailing! She takes her time to ensure every single nail is symmetrical and smooth. The salon vibes are peaceful and comfortable.",
    attachedPhoto: null,
    likesCount: 3,
    responseFromOwner: null
  },
  {
    id: "rev-16",
    author: "Bushra Ansari",
    avatarColor: "#f59f00",
    initials: "BA",
    isLocalGuide: true,
    reviewsCount: 45,
    rating: 5,
    relativeTime: "4 months ago",
    serviceTag: "Bridal Nails & 3D Art",
    text: "Hands down the best nail technician in the city. The 3D pearls and crystal stones were placed with extreme precision. Even when lifting heavy lehengas, not a single crystal came off.",
    attachedPhoto: "assets/images/royal-bridal-stiletto.jpg",
    likesCount: 19,
    responseFromOwner: null
  },
  {
    id: "rev-17",
    author: "Samia Qureshi",
    avatarColor: "#40c057",
    initials: "SQ",
    isLocalGuide: false,
    reviewsCount: 9,
    rating: 5,
    relativeTime: "4 months ago",
    serviceTag: "Acrylic Extensions",
    text: "Got square shape acrylics with French tips. Cleanest lines ever. Rabiaa is very patient and explains the aftercare tips thoroughly. Definitely coming back for my infill.",
    attachedPhoto: null,
    likesCount: 5,
    responseFromOwner: null
  },
  {
    id: "rev-18",
    author: "Urooj Khalid",
    avatarColor: "#fa5252",
    initials: "UK",
    isLocalGuide: true,
    reviewsCount: 18,
    rating: 5,
    relativeTime: "4 months ago",
    serviceTag: "3D Bows & Gems",
    text: "The 3D bow design she did for me became viral in my family WhatsApp group! Her hand-painted detailing is next level. Top rated studio for a reason.",
    attachedPhoto: "assets/images/korean-jelly-bows.jpg",
    likesCount: 14,
    responseFromOwner: "Haha, so happy your family loved it Urooj! Thank you!"
  },
  {
    id: "rev-19",
    author: "Mehreen Shah",
    avatarColor: "#22b8cf",
    initials: "MS",
    isLocalGuide: false,
    reviewsCount: 2,
    rating: 5,
    relativeTime: "5 months ago",
    serviceTag: "Deluxe Spa Pedicure",
    text: "Very soothing pedicure experience. My heels feel like a baby's skin and the French toe paint looks crisp. Booking via WhatsApp was smooth and prompt.",
    attachedPhoto: "assets/images/deluxe-spa-pedicure.jpg",
    likesCount: 2,
    responseFromOwner: null
  },
  {
    id: "rev-20",
    author: "Hira Mansoor",
    avatarColor: "#e8590c",
    initials: "HM",
    isLocalGuide: true,
    reviewsCount: 35,
    rating: 5,
    relativeTime: "5 months ago",
    serviceTag: "French Ombré",
    text: "I live in Clifton but travel all the way to Dalmia Cement Road just for Rabiaa's nail artistry. Nobody in Defense/Clifton delivers this level of durability and finish at such reasonable rates. 10/10.",
    attachedPhoto: "assets/images/french-ombre-almond.jpg",
    likesCount: 23,
    responseFromOwner: "Thank you so much Hira for traveling to us! Your loyalty means the world to us."
  },
  {
    id: "rev-21",
    author: "Sadia Kamran",
    avatarColor: "#862e9c",
    initials: "SK",
    isLocalGuide: false,
    reviewsCount: 14,
    rating: 5,
    relativeTime: "6 months ago",
    serviceTag: "Acrylic Extensions",
    text: "Perfect stiletto shape with matte burgundy topcoat. Zero lifting even at 4 weeks. Rabiaa is an artist with real passion for her craft.",
    attachedPhoto: null,
    likesCount: 7,
    responseFromOwner: null
  },
  {
    id: "rev-22",
    author: "Tania Lodhi",
    avatarColor: "#12b886",
    initials: "TL",
    isLocalGuide: true,
    reviewsCount: 29,
    rating: 5,
    relativeTime: "6 months ago",
    serviceTag: "Russian Gel Manicure",
    text: "Gentle on natural nails. Removal is always done with care, never peeling or ripping off the natural nail plate. Highly educated on nail anatomy and hygiene.",
    attachedPhoto: "assets/images/russian-natural-biab.jpg",
    likesCount: 11,
    responseFromOwner: null
  },
  {
    id: "rev-23",
    author: "Yumna Rasheed",
    avatarColor: "#e03131",
    initials: "YR",
    isLocalGuide: false,
    reviewsCount: 6,
    rating: 5,
    relativeTime: "7 months ago",
    serviceTag: "3D Bows & Gems",
    text: "Loved my pink jelly nails with 3D sculpted bows and crystal droplets. It felt like living in a fairytale. Best nail artist in Karachi!",
    attachedPhoto: "assets/images/korean-jelly-bows.jpg",
    likesCount: 8,
    responseFromOwner: null
  },
  {
    id: "rev-24",
    author: "Warda Baig",
    avatarColor: "#3b5bdb",
    initials: "WB",
    isLocalGuide: true,
    reviewsCount: 15,
    rating: 5,
    relativeTime: "8 months ago",
    serviceTag: "Bridal Nails & 3D Art",
    text: "Booked a pre-wedding bridal package. From the exfoliating hand massage to the final glossy top coat, everything was pure bliss. My wedding photos with the henna and nail art turned out magical.",
    attachedPhoto: "assets/images/signature-bridal-3d-nails.png",
    likesCount: 17,
    responseFromOwner: "Congratulations Warda! So pleased to hear you loved the bridal set."
  },
  {
    id: "rev-25",
    author: "Amber Nisar",
    avatarColor: "#099268",
    initials: "AN",
    isLocalGuide: false,
    reviewsCount: 8,
    rating: 5,
    relativeTime: "9 months ago",
    serviceTag: "BIAB / Builder Gel",
    text: "Rabiaa is very warm and courteous. The studio space is cozy and very clean. My builder gel nails survived housework, typing, and cooking without a scratch.",
    attachedPhoto: null,
    likesCount: 6,
    responseFromOwner: null
  },
  {
    id: "rev-26",
    author: "Zoya Kashif",
    avatarColor: "#c2255c",
    initials: "ZK",
    isLocalGuide: true,
    reviewsCount: 48,
    rating: 5,
    relativeTime: "10 months ago",
    serviceTag: "Acrylic Extensions",
    text: "The best nail studio in Callachi Society / Dalmia area. Professional acrylic extensions that feel lightweight yet super durable. 240+ 5-star reviews are totally well deserved!",
    attachedPhoto: "assets/images/velvet-cateye-coffin.jpg",
    likesCount: 13,
    responseFromOwner: "Thank you Zoya! We appreciate your support and love."
  }
];

const REVIEWS_SUMMARY = {
  averageRating: 4.9,
  totalReviews: 240,
  breakdown: {
    fiveStar: 96,
    fourStar: 3,
    threeStar: 1,
    twoStar: 0,
    oneStar: 0
  },
  recommendationRate: "99%",
  verifiedCount: 240
};
